name: down_care
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^4.0.4
  flutter_svg: ^1.0.0
  camera: ^0.11.0+2
  image_picker: ^0.8.4+4
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  http: ^1.2.2
  geocoding: ^3.0.0
  image: ^4.3.0
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  google_sign_in: ^5.4.2
  shared_preferences: ^2.0.8
  firebase_storage: ^12.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: "^0.14.1"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/
    - assets/dr-okkian.jpg
    - assets/trisomi21.jpeg
    - assets/Mosaik.jpg
    - assets/Translokasi.jpg
    # - assets/icon/home.svg
    # - assets/icon/camera.svg
    # - assets/icon/profile-circle.svg
    # - assets/icon/trend-up.svg
    # - assets/icon/calendar.svg
    # - assets/icon/map.svg
    # - assets/icon/kids.svg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "assets/app_icon.png"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_native_splash:
  color: "#2D60FF"
  image: assets/logo.png
  android: true
  ios: true
  android_12:
    color: "#2D60FF"
    image: assets/splash.png
