// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlx0-VM2-LYxgcmmC4MxsIttlym-S1oZI',
    appId: '1:1073969707112:web:c188638bb80734fa0c23dd',
    messagingSenderId: '1073969707112',
    projectId: 'mobile-pbl-app',
    authDomain: 'mobile-pbl-app.firebaseapp.com',
    storageBucket: 'mobile-pbl-app.firebasestorage.app',
    measurementId: 'G-YQDFFSN4HG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAotLFVX5kL8KlmBFlalTy1AN084Hgf-84',
    appId: '1:1073969707112:android:0f9e7f64ade857220c23dd',
    messagingSenderId: '1073969707112',
    projectId: 'mobile-pbl-app',
    storageBucket: 'mobile-pbl-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiAYDxRDR1dQyWb7cwIv-SU5ofVCtRCuw',
    appId: '1:1073969707112:ios:6be60295d4877c1c0c23dd',
    messagingSenderId: '1073969707112',
    projectId: 'mobile-pbl-app',
    storageBucket: 'mobile-pbl-app.firebasestorage.app',
    androidClientId: '1073969707112-ftf47t4jf0o7c54ka88khho2sif78e67.apps.googleusercontent.com',
    iosClientId: '1073969707112-n0nq6op2946aid5cm6ks4hd70ddbacka.apps.googleusercontent.com',
    iosBundleId: 'com.example.downCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiAYDxRDR1dQyWb7cwIv-SU5ofVCtRCuw',
    appId: '1:1073969707112:ios:6be60295d4877c1c0c23dd',
    messagingSenderId: '1073969707112',
    projectId: 'mobile-pbl-app',
    storageBucket: 'mobile-pbl-app.firebasestorage.app',
    androidClientId: '1073969707112-ftf47t4jf0o7c54ka88khho2sif78e67.apps.googleusercontent.com',
    iosClientId: '1073969707112-n0nq6op2946aid5cm6ks4hd70ddbacka.apps.googleusercontent.com',
    iosBundleId: 'com.example.downCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlx0-VM2-LYxgcmmC4MxsIttlym-S1oZI',
    appId: '1:1073969707112:web:fd08127c21166d6f0c23dd',
    messagingSenderId: '1073969707112',
    projectId: 'mobile-pbl-app',
    authDomain: 'mobile-pbl-app.firebaseapp.com',
    storageBucket: 'mobile-pbl-app.firebasestorage.app',
    measurementId: 'G-GRLV80G1QG',
  );

}